spring.application.name=landslide-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/landslide_db
spring.datasource.username=root
spring.datasource.password=monu2007

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# ML Service URL
ml.service.url=http://localhost:8000
